Explicitly convert values of contract type to address - solc. 0.5.0 breaking change
Fixed:
```
TypeError: Type contract TokenNetwork is not implicitly convertible to expected type address.
```