Better error message for missing command argument
When --token-network-registry-address was missing, the
deployment script showed a mysterious error
```
TypeError: One or more arguments could not be encoded to the necessary ABI type.  Expected types are: address, address, address, address
```

After this commit, the error message is much easier.
```
Error: Missing option "--token-network-registry-address".
```

This fixes #1168.